replicaCount: 2

ingress:
  enabled: false
  className: ""
  annotations: {}
    ingress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod-dns01
    acme.cert-manager.io/http01-edit-in-place: "true"
  hosts:
    - host: dev.kudratillo.org
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
   - secretName: artesmi-dev
     hosts:
       - dev.kudratillo.org